
both:
	
	include:
		cfg:
			loader:
				example: '/public/script/loader/examples.js'
	
	routes:
		public : '/public/script/{0}.js' 
		public.compo: '/public/compo/{0}/{1}.js' 
		
		atma: '/.reference/atma/{0}/lib/{1}.js'
		atma.compos: '/.reference/atma/compos/{0}/lib/{1}.js'
	
		view: '/public/view/{0}/{1}.js'
	
	scripts:
		atma:
			- ruqq/arr
			
		atma.compos:
			- pre-indent
			- prism
			- layout
			- tabs
			- radio
			- markdown
			
		public.compo:
			- scroller
			- navigation
			- view/default
			- view/viewManager
			- user/userInfo
			
			
		