


client:
	
	include:
		src: '/.reference/atma/include/lib/include.js'
		
		
	scripts:
		atma:
			- ruqq/dom/jquery
			- class
			- mask
			- if#debug:
				- mask/plugin.reload
			- ruqq/ruqq.base
			- ruqq/utils
			- mask.node/mask.bootstrap
			- ruta
			- mask.animation
			- if#debug:
				- include/include.autoreload
			
		public.compo:
			- spinner
			- pageActivity
			- downloader
			- sourceViewer
			- overlay
		
	styles:
		- '/public/style/main.less'
		- '/public/compo/view/view.less'